{{- $fullName := include "hinge-service.fullName" . -}}
{{- $svcPort := .Values.servicePort -}}

{{- if .Values.customerFacingIngressEnabled -}}

  # {{- if .Values.customerFacingIngressExternalDomain }}
  #   {{- $externalDomain := .Values.customerFacingIngressExternalDomain | default ""}}
  # {{- end }}

  {{- $backendDomain := .Values.customerFacingDomain }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-customer-facing
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hinge-service.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: alb
  {{- if .Values.customerFacingIngressAllowSourceCidrs }}
    alb.ingress.kubernetes.io/inbound-cidrs: {{ join "," .Values.customerFacingIngressAllowSourceCidrs }}
  {{- end }}
  {{- if eq .Values.customerFacingIngressInternal true }}
    alb.ingress.kubernetes.io/group.name: "{{.Values.clusterName}}-customer-facing-internal"
    alb.ingress.kubernetes.io/scheme: internal
  {{- else }}
    alb.ingress.kubernetes.io/group.name: "{{.Values.clusterName}}-customer-facing-internet-facing"
    alb.ingress.kubernetes.io/scheme: internet-facing
  {{- end }}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-protocol: "{{ .Values.customerFacingIngressHealthCheckProtocol }}"
    alb.ingress.kubernetes.io/healthcheck-path: "{{ .Values.customerFacingIngressHealthCheckPath }}"
    alb.ingress.kubernetes.io/healthcheck-port: "{{ .Values.customerFacingIngressHealthCheckPort | default .Values.containerPort }}"
    alb.ingress.kubernetes.io/success-codes: "{{ .Values.customerFacingIngressHealthCheckSuccessCodes }}"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-Ext-2018-06"
  {{- if .Values.customerFacingIngressCertificateArn }}
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.customerFacingIngressCertificateArn }}"
  {{- end }}
spec:
  rules:
    - host: {{ .Values.customerFacingIngressUrl }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.servicePort }}
{{- end }}
